# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class HardwareProfile(Model):
    """Specifies the hardware settings for the AzureBareMetal instance.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar hardware_type: Name of the hardware type (vendor and/or their
     product name). Possible values include: 'Cisco_UCS', 'HPE'
    :vartype hardware_type: str or
     ~microsoft.baremetalinfrastructure.models.AzureBareMetalHardwareTypeNamesEnum
    :ivar azure_bare_metal_instance_size: Specifies the AzureBareMetal
     instance SKU. Possible values include: 'S72m', 'S144m', 'S72', 'S144',
     'S192', 'S192m', 'S192xm', 'S96', 'S112', 'S224', 'S224m', 'S224om',
     'S224oo', 'S224oom', 'S224ooo', 'S384', 'S384m', 'S384xm', 'S384xxm',
     'S448', 'S448m', 'S448om', 'S448oo', 'S448oom', 'S448ooo', 'S576m',
     'S576xm', 'S672', 'S672m', 'S672om', 'S672oo', 'S672oom', 'S672ooo',
     'S768', 'S768m', 'S768xm', 'S896', 'S896m', 'S896om', 'S896oo', 'S896oom',
     'S896ooo', 'S960m'
    :vartype azure_bare_metal_instance_size: str or
     ~microsoft.baremetalinfrastructure.models.AzureBareMetalInstanceSizeNamesEnum
    """

    _validation = {
        'hardware_type': {'readonly': True},
        'azure_bare_metal_instance_size': {'readonly': True},
    }

    _attribute_map = {
        'hardware_type': {'key': 'hardwareType', 'type': 'str'},
        'azure_bare_metal_instance_size': {'key': 'azureBareMetalInstanceSize', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(HardwareProfile, self).__init__(**kwargs)
        self.hardware_type = None
        self.azure_bare_metal_instance_size = None
